### ISSUE TITLE
rahulmaurya1507@gmail.com

### ISSUE THREAD

**Issue by rahulmaurya1507** [opentargets/standalone-deployment-platform#5]
I am trying to run the `standalone-deployment-platform` repository to access the open-targets UI from my local. 

This is the docker compose content for ot-es container which is causing some `java.lang.UnsupportedOperationException: sun.misc.Unsafe unavailable` error. I have tried to resolve this issue but have been unsuccessful and got nowhere close to resolving it.

```markdown
  elasticsearch:
    image: ${OTOPS_PROFILE_ELASTIC_SEARCH_DOCKER_IMAGE_NAME}:${OTOPS_PROFILE_ELASTIC_SEARCH_DOCKER_IMAGE_TAG}
    container_name: ot-es
    ports:
      - "9200:9200"
      - "9300:9600"
    environment:
      - "path.data=/usr/share/opensearch/data"
      - "path.logs=/usr/share/opensearch/logs"
      - "cluster.name=ot-es-cluster"
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
      - "discovery.seed_hosts=[]"
      - "bootstrap.memory_lock=true"
      - "search.max_open_scroll_context=5000"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "logger.level=DEBUG"
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx4g"
    volumes:
      - "esdata:/usr/share/opensearch/data"
    ulimits:
      memlock: -1
      nofile: 65536
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - ot-platform
```
I am attaching the logs generated from the `ot-es` container for the referance. Kindly help me with this regards. @
[ot-es.log](https://github.com/user-attachments/files/17072902/ot-es.log)

**Comment by rahulmaurya1507** [comment]
Thank you for your prompt response.

Sharing additional details:
1. Profiles: I used multiple profiles `config.dev, config.2403, config.2406`.
2.  OS & Version: Ubuntu 22.04 and Ubuntu 24.04
3. Docker Version: 27.2.1, build 9e34c9b

Please do let me know if any additional information is required.

**Comment by kenibrewer** [comment]
I've been getting the same error messages as well. Also from Ubuntu 22.04 but using docker version 24.0.7.

**Comment by kenibrewer** [comment]
Here are the logs of what I'm getting with my deploy. It also includes the `java.lang.UnsupportedOperationException: sun.misc.Unsafe unavailable` message. 

[ot-es.log](https://github.com/user-attachments/files/17091377/ot-es.log)

**Comment by rahulmaurya1507** [comment]
Dear @mbdebian, has there been any update in the issue? I tried resolving it but still no success.

**Comment by remo87** [comment]
@rahulmaurya1507  Issue 5 seems to something different to your issue but in your case the command `chmod 777 -R deployment` should work. This is an issue with the folder permissions. We'll create an item to work in a permanent solution for Linux.

**Comment by remo87** [comment]
@rahulmaurya1507  we've done a fix that might help you if you pull the latest version

**Comment by rahulmaurya1507** [comment]
Sounds great. I'll try it out.

Thanks

**Comment by mbdebian** [comment]
This is now addressed
