### ISSUE TITLE
Container ot-es is Unhealthy

### ISSUE THREAD

**Issue by shaileshchaudhary11** [opentargets/standalone-deployment-platform#6]
Hi,

I am encountering an issue with the ot-es container in my setup. When I attempt to run the application, the container is marked as unhealthy, and I receive the following error:

![image](https://github.com/user-attachments/assets/bd84cb2d-9791-476c-9dcb-60511fb62a8a)

make: *** [Makefile:123: platform_up] Error 1

I've tried restarting the container and checking the logs for any clues, but I am unable to resolve the issue. I am attaching
[ot-es.log](https://github.com/user-attachments/files/17162561/ot-es.log)
 log file for further details below.

Here are the details of my setup:

Docker version 27.3.1, build ce12230
Operating System:  Ubuntu 22.04.5 LTS
Profile: config.2406-gcs
OpenJDK version 11.0.24

I am following blog ( https://blog.opentargets.org/standalone-deployment-tool/ )
for setting up open target.

Could any one please assist me in troubleshooting this issue? Any help would be greatly appreciated!

Thank you!

**Comment by mbdebian** [comment]
Thanks for reporting @shaileshchaudhary11 , would you mind providing the configuration profile you're using, so we can reproduce the issue on our side and investigate what may be happening?
Thanks!

**Comment by remo87** [comment]
It could be a permissions issue with the `es` try making the `deployment` folder readable for everyone `chmod 777 -R deployment` and re start the container

**Comment by shaileshchaudhary11** [comment]
> Thanks for reporting @shaileshchaudhary11 , would you mind providing the configuration profile you're using, so we can reproduce the issue on our side and investigate what may be happening? Thanks!

Profile : config.2406-gcs

**Comment by shaileshchaudhary11** [comment]
Hi @mbdebian, any updates on above issue, have you try to run it?

**Comment by remo87** [comment]
You're right @shaileshchaudhary11 the permission change solves a different issue. I just tried cleaning my env and running the standalone with the same profile as you but it worked. I ran it in a Ubuntu 22.04.5 LTS which is the same version as yours. Could you please share console output to see if there's potential issues?

![image](https://github.com/user-attachments/assets/b3da9daa-c88e-4479-9f01-c04b8da42482)

**Comment by shaileshchaudhary11** [comment]
Hii @remo87 

Can you please tell me what commands did you  run in sequence in the terminal?
I would like to try the exact same thing.

Also, Is there any other even a slight change in any file of the project that you made?

**Comment by remo87** [comment]
sure thing!

``` bash
 8281  2024-09-30 09:22:39 make platform_down
 8283  2024-09-30 09:23:00 sudo make clean
 8285  2024-09-30 09:23:52 make set_profile profile=2406-gcs
 8286  2024-09-30 09:24:09 make platform_up
```

I was testing with a different profile so I had different data and versions in my local environment. To test your configuration I ran `make platform_down` to destroy the containers and `sudo make clean` to delete the local files.

I did not changed the profile `config.2406-gcs` did a pull from master and my local repo has no changes.

**Comment by remo87** [comment]
I forgot to mention that after the previous steps I also performed the `chmod` operation

**Comment by remo87** [comment]
@shaileshchaudhary11 we've done a fix that might help you if you pull the latest version

**Comment by mbdebian** [comment]
This has now been addressed, please, let us know in case you face any more issues.
Thanks!

**Comment by shaileshchaudhary11** [comment]
Thank you, now I am able to run the Open Target platform at my local
machine using standalone-deployment-platform. I have a doubt there is Open
Target Genetics platform, is there any repository to run this platform also
on my local machine .

**Comment by mbdebian** [comment]
I have reproduce this environment in Google Cloud, as we don't have yet an allocation in AWS, specs:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

Docker version 27.3.1, build ce12230
docker-compose version 1.29.2, build unknown
```

I've run this using the profile ```config.2406-gcs```, which downloads the data volumes from our bucket in Google Cloud, and profile ```config.2406```, which is the same, but the _tarballs_ are downloaded from our EBI FTP location.

No JDK is needed, as everything is run via docker images.

When installing _Docker_, the regular user has been added to the _docker_ group, so no root permission is needed for running the containers.

The changes can be found in branch ```local_issue_6_and_8```.

@kenibrewer, would you mind trying this branch, with profile '2406' in your EC2 instance?

Thank you guys!

**Comment by kenibrewer** [comment]
Thanks @mbdebian . Your theory about the requester pays bucket seems solid to me. I'll test out the changes and let you know.

**Comment by kenibrewer** [comment]
Hi @mbdebian This fixed the problem for me, and I was able to get a working deployment. Thanks so much!
