### ISSUE TITLE
Ongoing problems with ot-es container

### ISSUE THREAD

**Issue by kenibrewer** [opentargets/standalone-deployment-platform#8]
Hi @mbdebian 

Just following up on #6. The recent changes you pushed failed to resolve the issues that we were having with the ot-es container on Ubuntu 24.04.01. 

Attached are the log files for ot-es container on our deployment which is a clean EC2 instance built from the standard AWS Ubuntu 24.04 AMI with `docker`, `docker compose` and `gsutil` their dependencies as the only additional tools installed on the image. 

[ot-es.log](https://github.com/user-attachments/files/17452081/ot-es.log)

The part of the logs that stands out to me are the lines before and after the `java.nio.file.NoSuchFileException` errors.

Have you tested the deployment of the standalone-deployment-platform on a clean VM or machine image? If so could you provide some more detailed instructions about your testing environment so we could replicate it for our deployment?

Thanks again for making such an exciting tool accessible to the research community!

**Comment by javfg** [comment]
Hi Ken,

This looks like a different problem than #6, the error you get is related to opensearch security analytics (there seems to be something similar [here](https://github.com/opensearch-project/security-analytics/issues/1312). We'll investigate.

Regarding our testing, we are not using the standalone deployment in cloud environments or vms, just in our physical machines.

I'll keep you posted if we find anything!

**Comment by AnneCarpenter** [comment]
Hi! I wonder if you uncovered anything to solve this? We are stuck here :(

**Comment by javfg** [comment]
We're currently finishing some big changes in the platform and haven't been able to check on this yet.

But it is still in our radar, we will get to it.

Sorry for the delay!

**Comment by mbdebian** [comment]
Hi @kenibrewer , please, have a look at #6 where I've made changes in a branch that I think will probably address your problem when deploying open targets in EC2.

I've verified those changes for a 22.04.5 LTS, but they're very likely to apply to your EC2 based Ubuntu 24.04.01.

Would you mind giving them a try while I set up another environment to mimic yours, so I can find out whether there may be differences between those Ubuntu versions that need to be addressed for the stand alone deployment tool to work?

Thanks @kenibrewer !

**Comment by kenibrewer** [comment]
Hi @mbdebian the fixes on the branch `local_issue_6_and_8` worked in resolving the issues with the `ot-es` container.
